import cpmpy as cp
import numpy as np
from .utils import make_assump_model, diversity, diversity_matrix
from itertools import combinations
from cpmpy.transformations.get_variables import get_variables


# just MARCO but returns MUSes as assump variables instead of constraints
def marco_assumps(soft, hard=[], solver="ortools", map_solver="ortools", return_mus=True, return_mcs=True, do_solution_hint=True, time_limit=None):
    """
        Enumerating minimal unsatisfiable subsets (MUSes) and minimal correction sets (MCSes)
        of unsatisfiable constraints.
        
        Iteratively generates a subset of constraints (the seed) and checks whether it is SAT.
        When the seed is SAT, it is grown to an MSS to derive an MCS.
        This MCS is then added to the Map solver as a set to hit
        In case the seed is UNSAT, the seed is shrunk to a real MUS and returned.
        The Map-solver is instructed to not generated any superset of this MUS as next seeds

        Based on:
            Liffiton, Mark H., et al. "Fast, flexible MUS enumeration." Constraints 21 (2016): 223-250.
    
        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: time_limit: time limit for a single solve call in seconds.
    """

    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)
    do_solution_hint = do_solution_hint and hasattr(map_solver, 'solution_hint')  # solver may not support solution hinting...

    map_solver += cp.any(assump)
    if do_solution_hint:
        hint = [1]*len(assump)
        map_solver.solution_hint(assump, hint) # we want large subsets, more likely to be a MUS

    deletion_order = {a : -len(get_variables(dmap[a])) for a in assump} # avoid recomputing

    while map_solver.solve(time_limit=time_limit):

        seed = [a for a in assump if a.value()]

        if s.solve(assumptions=seed, time_limit=time_limit) is True:
            # SAT, grow, to full MSS
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in set(assump) - set(mss):
                if s.solve(assumptions=mss + [to_add], time_limit=time_limit) is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if return_mcs:
                yield "MCS", mcs


        else: # UNSAT, shrink to MUS, re-use MUSX
            core = set(s.get_core())
            for c in sorted(core, key=deletion_order.get):
                if c not in core: # already removed
                    continue
                core.remove(c)
                if s.solve(assumptions=list(core), time_limit=time_limit) is True:
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver

            if return_mus:
                yield "MUS", core

        # ensure solution hint is still active
        if do_solution_hint:
            map_solver.solution_hint(assump, hint)



# enumerate a fixed amount i MUSes, compute the diversity matrix, select the subset with the highest diversity and return it.
def marco_select_top_k(constraints, k, i, solver="exact", map_solver="exact"): 
    muses = []

    for j, (_, mus) in enumerate(marco_assumps(constraints, solver=solver, map_solver=map_solver, return_mcs=False)):
        muses.append(mus)
        if j == i:
            break
    
    div_matrix = diversity_matrix(muses)
    top_indx, _ = select_top_k(div_matrix, k)
    top_muses = [muses[i] for i in top_indx]

    return top_muses


# enumerate MUSes with marco, at every iteration grow the diversity matrix and
# return the top k diverse MUSes when diversity of 1 is reached or after max iterations i
def marco_until_diverse(constraints, k, i, solver="exact", map_solver="exact"):
    
    # initiate list and matrix
    muses = []
    div_matrix = np.empty((1,1), dtype=float)
    div_matrix[0, 0] = 0
    
    # print("Starting to enumerate MUSes ...")
    top_indx = None
    avg = 0

    for j, (_, mus) in enumerate(marco_assumps(constraints, solver=solver, map_solver=map_solver, return_mcs=False)):
        muses.append(mus)

        if j > 0:
            div_matrix = np.pad(div_matrix, ((0, 1), (0, 1)) ,mode="constant")

        # print(f"Found MUS number {j}")
        
        for l in range(len(muses)-1):
            # print(f"Diversity between MUS {j} and MUS {l}: {diversity(muses[l], mus)}")
            div_matrix[l,j] = diversity(muses[l], mus)
        
        # print(f"The diversity matrix is now: \n {div_matrix}.")

        if j == k:
            top_indx, avg = select_top_k(div_matrix, k,incremental_last=False)
            # print(f"Current max average: {avg}")
            if avg >= 1:
                break

        if j > k:
            top_indx, avg = select_top_k(div_matrix, k,incremental_last=True, max_comb=top_indx, max_avg=avg)
            # print(f"Current max average: {avg}")
            if avg >= 1:
                break

        if j == i:
            break

    top_muses = [muses[i] for i in top_indx]
    
    return top_muses


def marco_diverse(soft, hard=[], solver="exact", map_solver="exact", return_mus=True, return_mcs=False, do_solution_hint=True, time_limit=None):
    """
        A modified version of MARCO where the Grow and Shrink procedures' selection order is favoring diversity, 
        and the solution hint is set to promote unseen constraints.

        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: time_limit: time limit for a single solve call in seconds.
    """
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)

    map_solver += cp.any(assump)

    if do_solution_hint and hasattr(map_solver, 'solution_hint'):
        map_solver.solution_hint(assump, [1]*len(assump)) # we want large subsets, more likely to be a MUS

    # deletion order based on already seen constraints
    # keep a map of which constraints are seen in previously generated MUSes
    seenmap = dict(zip(assump, [0]*len(assump)))
    
    while map_solver.solve(time_limit=time_limit):

        seed = [a for a in assump if a.value()]

        if s.solve(assumptions=seed, time_limit=time_limit) is True:
            # SAT, grow, to full MSS
            # Grow with already seen *similar* !! constraints first 
            # (a blocked similar MCS will stimulate more diverse MUS)

            
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in sorted(set(assump) - set(mss), key=seenmap.get):
                if s.solve(assumptions=mss + [to_add], time_limit=time_limit) is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if return_mcs:
                yield "MCS", core # , [dmap[a] for a in mcs]


        else: 
            # UNSAT, shrink to MUS, re-use MUSX
            # Shrink with already seen constraints first 
            # (remove similarity in MUSes) 

            core = set(s.get_core())
            for c in sorted(core, key=seenmap.get, reverse=True):
                if c not in core: # already removed
                    continue
                core.remove(c)
                if s.solve(assumptions=list(core), time_limit=time_limit) is True:
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver
            
            # update seenmap
            for a in core:
                seenmap[a] += 1

            if return_mus:
                yield "MUS", core # , [dmap[a] for a in core]

        map_solver.minimize(cp.sum([seenmap[a] for a in assump]*assump)) 



# enumerate k amount of MUSes with ocus, updating the objective every iteration (minimize the constraints that are already found)
# and block the previously found MUSes in the hitting set solver
# ORTOOLS appears to be faster here than the exact solver for hitting set computation
def ocus_enum(soft, hard=[], solver="ortools", hs_solver="gurobi", time_limit=None):
    
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), f"optimal_mus requires a solver that supports assumption variables, use optimal_mus_naive with {solver} instead"
    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    seenmap = dict(zip(assump, [1]*len(assump)))
    
    s = cp.SolverLookup.get(solver, model)
    assert s.solve(assumptions=assump, time_limit=time_limit) is False

    # initialize hitting set solver
    hs_solver = cp.SolverLookup.get(hs_solver)

    # generate MUSes loop
    while True:
        seen = [seenmap[a] for a in assump]
        hs_solver.minimize(cp.sum(assump * np.array(seen)))

        # hitting set loop
        while hs_solver.solve(time_limit=time_limit) is True:
            hitting_set = [a for a in assump if a.value()]
            if s.solve(assumptions=hitting_set, time_limit=time_limit) is False:
                break

            # else, the hitting set is SAT, now try to extend it without extra solve calls.
            # Check which other assumptions/constraints are satisfied (using c.value())
            # complement of grown subset is a correction subset
            # Assumptions encode indicator constraints a -> c, find all false assumptions
            #   that really have to be false given the current solution.
            new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
            hs_solver += cp.sum(new_corr_subset) >= 1

            # greedily search for other corr subsets disjoint to this one
            sat_subset = list(new_corr_subset)
            while s.solve(assumptions=sat_subset, time_limit=time_limit) is True:
                new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
                sat_subset += new_corr_subset # extend sat subset with new corr subset, guaranteed to be disjoint
                hs_solver += cp.sum(new_corr_subset) >= 1 # add new corr subset to hitting set solver
        inc = len(hitting_set)
        for a in hitting_set:
            seenmap[a] += inc
        # block found MUS in hitting set solver
        hs_solver += ~cp.all(hitting_set)
        yield hitting_set, [dmap[a] for a in hitting_set]
    


# enumerate k amount of MUSes with ocus, updating the objective every iteration (minimize the constraints that are already found)
# and block the previously found MUSes in the hitting set solver
# ORTOOLS appears to be faster here than the exact solver for hitting set computation
# VERSION WHERE WEIGHTS ARE ZERO FOR UNSEEN CONSTRAINTS AND WITH SHRINKING
def ocus_enum_shrink(soft, hard=[], solver="ortools", hs_solver="gurobi", time_limit=None):
    
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), f"optimal_mus requires a solver that supports assumption variables, use optimal_mus_naive with {solver} instead"
    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    # first MUS to compute is smallest MUS
    seenmap = dict(zip(assump, [1]*len(assump)))
    
    s = cp.SolverLookup.get(solver, model)
    assert s.solve(assumptions=assump, time_limit=time_limit) is False

    # initialize hitting set solver
    hs_solver = cp.SolverLookup.get(hs_solver)
    first = True
    # generate MUSes loop
    while True:
        seen = [seenmap[a] for a in assump]
        hs_solver.minimize(cp.sum(assump * np.array(seen)))

        # hitting set loop
        while hs_solver.solve(time_limit=time_limit) is True:
            hitting_set = [a for a in assump if a.value()]
            if s.solve(assumptions=hitting_set, time_limit=time_limit) is False:
                break

            # else, the hitting set is SAT, now try to extend it without extra solve calls.
            # Check which other assumptions/constraints are satisfied (using c.value())
            # complement of grown subset is a correction subset
            # Assumptions encode indicator constraints a -> c, find all false assumptions
            #   that really have to be false given the current solution.
            new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
            hs_solver += cp.sum(new_corr_subset) >= 1

            # greedily search for other corr subsets disjoint to this one
            sat_subset = list(new_corr_subset)
            while s.solve(assumptions=sat_subset, time_limit=time_limit) is True:
                new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
                sat_subset += new_corr_subset # extend sat subset with new corr subset, guaranteed to be disjoint
                hs_solver += cp.sum(new_corr_subset) >= 1 # add new corr subset to hitting set solver
        
        # shrink to a MUS
        for c in sorted(hitting_set):
            if c not in hitting_set: # already removed
                continue
            hitting_set.remove(c)
            if s.solve(assumptions=list(hitting_set), time_limit=time_limit):
                hitting_set.add(c)
            else: # UNSAT, shrink to new solver core (clause set refinement)
                hitting_set = set(s.get_core())

        # when first MUS (smallest) is found, reset all weights to zero
        if first:
            first = False
            seenmap = dict(zip(assump, [0]*len(assump)))

        for a in hitting_set:
            seenmap[a] += 1
        # block found MUS in hitting set solver
        hs_solver += ~cp.all(hitting_set)
        yield hitting_set, [dmap[a] for a in hitting_set]



# helper function
def select_top_k(matrix, k, incremental_last=False, max_comb=None, max_avg = 0):
    """
        Returns a tuple with the indeces of the top-k highest average in the matrix.

        :param: matrix: the upper triangular matrix with values
        :param: k: the size of the top subset to be computed
        :param: incremental_last: whether only the combinations with the last element
             in it are computed because this function is used incrementally.
    """

    n = len(matrix)

    if k <= 0 or n<=1:
        return max_comb, max_avg
    
    total_pairs = k * (k - 1) / 2.0

    if incremental_last:

        last = n - 1
        for base in combinations(range(n-1),k-1):
            comb = base + (last,)
            # print(f"combination: {comb}")
            curr_sum = 0
            for indx in combinations(comb, 2):
                curr_sum += matrix[indx]
                # print(f"taking avg elem: {matrix[indx]}")

            curr_avg = curr_sum / total_pairs
            # print(f"The avg div of this combination was: {curr_avg}.")

            if curr_avg > max_avg:
                max_avg = curr_avg
                max_comb = comb
    
    else:
        for comb in combinations(range(n), k):
            curr_sum = 0
            # print(f"combination: {comb}")
            for indx in combinations(comb, 2):
                # print(f"taking avg elem: {matrix[indx]}")
                curr_sum += matrix[indx]
        
            curr_avg = curr_sum / total_pairs
            # print(f"The avg div of this combination was: {curr_avg}.")

            if curr_avg > max_avg:
                max_avg = curr_avg
                max_comb = comb

    return max_comb, max_avg