
import cpmpy as cp
import numpy as np
from .utils import make_assump_model
from cpmpy.transformations.get_variables import get_variables
import time


def remaining_time(deadline):
    """Seconds left in the global budget, or None if unlimited."""
    if deadline is None:
        return None
    return deadline - time.monotonic()


def timed_solve(solver, deadline, **kwargs):
    """
        Solve with remaining global time.
        Returns solver result, or None if the global time budget is exhausted.
    """
    rem = remaining_time(deadline)
    if rem is not None and rem <= 0:
        return None
    solver.solve(time_limit=rem, **kwargs)
    status = solver.status()
    print("status")
    if status.exitstatus == cp.ExitStatus.OPTIMAL or status.exitstatus == cp.ExitStatus.FEASIBLE:
        return True
    elif status.exitstatus == cp.ExitStatus.UNSATISFIABLE:
        return False
    elif status.exitstatus == cp.ExitStatus.UNKNOWN:
        return None 
    else:
        return None


# just MARCO but returns MUSes as assump variables instead of constraints
def marco_assumps(soft, hard=[], solver="ortools", map_solver="ortools", return_mus=True, return_mcs=False, do_solution_hint=True, time_limit=None):
    """
        Enumerating minimal unsatisfiable subsets (MUSes) and minimal correction sets (MCSes)
        of unsatisfiable constraints.
        
        Iteratively generates a subset of constraints (the seed) and checks whether it is SAT.
        When the seed is SAT, it is grown to an MSS to derive an MCS.
        This MCS is then added to the Map solver as a set to hit
        In case the seed is UNSAT, the seed is shrunk to a real MUS and returned.
        The Map-solver is instructed to not generated any superset of this MUS as next seeds

        Based on:
            Liffiton, Mark H., et al. "Fast, flexible MUS enumeration." Constraints 21 (2016): 223-250.
    
        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: time_limit: total global time budget in seconds.
    """
    start_time = time.monotonic()
    deadline = None if time_limit is None else start_time + time_limit

    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)
    do_solution_hint = do_solution_hint and hasattr(map_solver, 'solution_hint')  # solver may not support solution hinting...

    map_solver += cp.any(assump)
    if do_solution_hint:
        hint = [1]*len(assump)
        map_solver.solution_hint(assump, hint) # we want large subsets, more likely to be a MUS

    deletion_order = {a : -len(get_variables(dmap[a])) for a in assump} # avoid recomputing

    while True:
        
        map_result = timed_solve(map_solver, deadline)
        if map_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return
        if map_result is False:
            return
        
        seed = [a for a in assump if a.value()]

        sat_result = timed_solve(s, deadline, assumptions=seed)
        if sat_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return

        if sat_result is True:
            # SAT, grow, to full MSS
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in set(assump) - set(mss):
                grow_result = timed_solve(s, deadline, assumptions=mss + [to_add])
                if grow_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if grow_result is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if return_mcs:
                yield "MCS", mcs, time.monotonic() - start_time


        else: # UNSAT, shrink to MUS, re-use MUSX
            core = set(s.get_core())
            for c in sorted(core, key=deletion_order.get):
                if c not in core: # already removed
                    continue
                core.remove(c)
                shrink_result = timed_solve(s, deadline, assumptions=list(core))
                if shrink_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if shrink_result is True:
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver

            if return_mus:
                yield "MUS", core, time.monotonic() - start_time

        # ensure solution hint is still active
        if do_solution_hint:
            map_solver.solution_hint(assump, hint)



def marco_diverse_Min_assump(soft, hard=[], solver="exact", map_solver="exact", return_mus=True, return_mcs=False, do_solution_hint=True, time_limit=None):
    """
        A modified version of MARCO where the Grow and Shrink procedures' selection order is favoring diversity, 
        and the solution hint is set to promote unseen constraints.

        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: time_limit: time limit for a single solve call in seconds.
    """
    start_time = time.monotonic()
    deadline = None if time_limit is None else start_time + time_limit
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)

    map_solver += cp.any(assump)

    if do_solution_hint and hasattr(map_solver, 'solution_hint'):
        map_solver.solution_hint(assump, [1]*len(assump)) # we want large subsets, more likely to be a MUS

    # deletion order based on already seen constraints
    # keep a map of which constraints are seen in previously generated MUSes
    seenmap = dict(zip(assump, [0]*len(assump)))
    
    while True:
        
        map_result = timed_solve(map_solver, deadline)
        if map_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return
        if map_result is False:
            return
        
        seed = [a for a in assump if a.value()]

        sat_result = timed_solve(s, deadline, assumptions=seed)
        if sat_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return

        if sat_result is True:
            # SAT, grow, to full MSS
            # Grow with already seen *similar* !! constraints first 
            # (a blocked similar MCS will stimulate more diverse MUS)

            
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in sorted(set(assump) - set(mss), key=seenmap.get):
                grow_result = timed_solve(s, deadline, assumptions=mss + [to_add])
                if grow_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if grow_result is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if return_mcs:
                yield "MCS", core # , [dmap[a] for a in mcs]


        else: 
            # UNSAT, shrink to MUS, re-use MUSX
            # Shrink with already seen constraints first 
            # (remove similarity in MUSes) 

            core = set(s.get_core())
            for c in sorted(core, key=seenmap.get, reverse=True):
                if c not in core: # already removed
                    continue
                core.remove(c)
                shrink_result = timed_solve(s, deadline, assumptions=list(core))
                if shrink_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if shrink_result is True:
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver
            
            # update seenmap
            for a in core:
                seenmap[a] += 1

            if return_mus:
                yield "MUS", core, time.monotonic() - start_time

        map_solver.minimize(cp.sum([seenmap[a] for a in assump]*assump)) 



def marco_diverse_noMin_assump(soft, hard=[], solver="exact", map_solver="exact", return_mus=True, return_mcs=False, do_solution_hint=True, time_limit=None):
    """
        A modified version of MARCO where the Grow and Shrink procedures' selection order is favoring diversity, 
        and the solution hint is set to promote unseen constraints.

        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: time_limit: time limit for a single solve call in seconds.
    """
    start_time = time.monotonic()
    deadline = None if time_limit is None else start_time + time_limit
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)

    map_solver += cp.any(assump)

    if do_solution_hint and hasattr(map_solver, 'solution_hint'):
        map_solver.solution_hint(assump, [1]*len(assump)) # we want large subsets, more likely to be a MUS

    # deletion order based on already seen constraints
    # keep a map of which constraints are seen in previously generated MUSes
    seenmap = dict(zip(assump, [0]*len(assump)))
    
    while True:
        
        map_result = timed_solve(map_solver, deadline)
        if map_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return
        if map_result is False:
            return
        
        seed = [a for a in assump if a.value()]

        sat_result = timed_solve(s, deadline, assumptions=seed)
        if sat_result is None:
            yield "TIMEOUT", None, time.monotonic() - start_time
            return

        if sat_result is True:
            # SAT, grow, to full MSS
            # Grow with already seen *similar* !! constraints first 
            # (a blocked similar MCS will stimulate more diverse MUS)

            
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in sorted(set(assump) - set(mss), key=seenmap.get):
                grow_result = timed_solve(s, deadline, assumptions=mss + [to_add])
                if grow_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if grow_result is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if return_mcs:
                yield "MCS", core # , [dmap[a] for a in mcs]


        else: 
            # UNSAT, shrink to MUS, re-use MUSX
            # Shrink with already seen constraints first 
            # (remove similarity in MUSes) 

            core = set(s.get_core())
            for c in sorted(core, key=seenmap.get, reverse=True):
                if c not in core: # already removed
                    continue
                core.remove(c)
                shrink_result = timed_solve(s, deadline, assumptions=list(core))
                if shrink_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if shrink_result is True:
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver
            
            # update seenmap
            for a in core:
                seenmap[a] += 1

            if return_mus:
                yield "MUS", core, time.monotonic() - start_time
        
        # ensure solution hint is still active
        if do_solution_hint:
            map_solver.solution_hint(assump, [seenmap[a] for a in assump])



# enumerate k amount of MUSes with ocus, updating the objective every iteration (minimize the constraints that are already found)
# and block the previously found MUSes in the hitting set solver
# ORTOOLS appears to be faster here than the exact solver for hitting set computation
def ocus_enum_1_assump(soft, hard=[], solver="ortools", hs_solver="gurobi", time_limit=None):
    
    start_time = time.monotonic()
    deadline = None if time_limit is None else start_time + time_limit
    
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), f"optimal_mus requires a solver that supports assumption variables, use optimal_mus_naive with {solver} instead"
    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    seenmap = dict(zip(assump, [1]*len(assump)))
    
    s = cp.SolverLookup.get(solver, model)

    # assert s.solve(assumptions=assump, time_limit=time_limit) is False

    # initialize hitting set solver
    hs_solver = cp.SolverLookup.get(hs_solver)

    # generate MUSes loop
    while True:
        seen = [seenmap[a] for a in assump]
        hs_solver.minimize(cp.sum(assump * np.array(seen)))

        # hitting set loop
        unsat_hitting_set = None
        while True:
            hs_result = timed_solve(hs_solver, deadline)
            if hs_result is None:
                yield "TIMEOUT", None, time.monotonic() - start_time
                return
            if hs_result is False:
                break
            
            hitting_set = [a for a in assump if a.value()]

            sat_result = timed_solve(s, deadline, assumptions=hitting_set)
            if sat_result is None:
                yield "TIMEOUT", None, time.monotonic() - start_time
                return
            if sat_result is False:
                unsat_hitting_set = hitting_set
                break

            # else, the hitting set is SAT, now try to extend it without extra solve calls.
            # Check which other assumptions/constraints are satisfied (using c.value())
            # complement of grown subset is a correction subset
            # Assumptions encode indicator constraints a -> c, find all false assumptions
            #   that really have to be false given the current solution.
            new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
            hs_solver += cp.sum(new_corr_subset) >= 1

            # greedily search for other corr subsets disjoint to this one
            sat_subset = list(new_corr_subset)
            while True:
                sat_result = timed_solve(s, deadline, assumptions=sat_subset)
                if sat_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if sat_result is False:
                    break
                new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
                sat_subset += new_corr_subset # extend sat subset with new corr subset, guaranteed to be disjoint
                hs_solver += cp.sum(new_corr_subset) >= 1 # add new corr subset to hitting set solver
                
        if unsat_hitting_set is None:
            return
        hitting_set = set(unsat_hitting_set)
        inc = len(hitting_set)
        for a in hitting_set:
            seenmap[a] += inc
        # block found MUS in hitting set solver
        hs_solver += ~cp.all(hitting_set)
        yield "MUS", hitting_set, time.monotonic() - start_time



# enumerate k amount of MUSes with ocus, updating the objective every iteration (minimize the constraints that are already found)
# and block the previously found MUSes in the hitting set solver
# ORTOOLS appears to be faster here than the exact solver for hitting set computation
# VERSION WHERE WEIGHTS ARE ZERO FOR UNSEEN CONSTRAINTS AND WITH SHRINKING
def ocus_enum_shrink_assump(soft, hard=[], solver="ortools", hs_solver="gurobi", time_limit=None):

    start_time = time.monotonic()
    deadline = None if time_limit is None else start_time + time_limit
    
    assert hasattr(cp.SolverLookup.get(solver), "get_core"), f"optimal_mus requires a solver that supports assumption variables, use optimal_mus_naive with {solver} instead"
    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    # first MUS to compute is smallest MUS
    seenmap = dict(zip(assump, [1]*len(assump)))
    
    s = cp.SolverLookup.get(solver, model)
    # assert s.solve(assumptions=assump, time_limit=time_limit) is False

    # initialize hitting set solver
    hs_solver = cp.SolverLookup.get(hs_solver)
    first = True
    # generate MUSes loop
    while True:
        seen = [seenmap[a] for a in assump]
        hs_solver.minimize(cp.sum(assump * np.array(seen)))

        # hitting set loop
        unsat_hitting_set = None
        while True:
            hs_result = timed_solve(hs_solver, deadline)
            if hs_result is None:
                yield "TIMEOUT", None, time.monotonic() - start_time
                return
            if hs_result is False:
                break
            
            hitting_set = [a for a in assump if a.value()]

            sat_result = timed_solve(s, deadline, assumptions=hitting_set)
            if sat_result is None:
                yield "TIMEOUT", None, time.monotonic() - start_time
                return
            if sat_result is False:
                unsat_hitting_set = hitting_set
                break 

            # else, the hitting set is SAT, now try to extend it without extra solve calls.
            # Check which other assumptions/constraints are satisfied (using c.value())
            # complement of grown subset is a correction subset
            # Assumptions encode indicator constraints a -> c, find all false assumptions
            #   that really have to be false given the current solution.
            new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
            hs_solver += cp.sum(new_corr_subset) >= 1

            # greedily search for other corr subsets disjoint to this one
            sat_subset = list(new_corr_subset)
            while True:
                sat_result = timed_solve(s, deadline, assumptions=sat_subset)
                if sat_result is None:
                    yield "TIMEOUT", None, time.monotonic() - start_time
                    return
                if sat_result is False:
                    break

                new_corr_subset = [a for a,c in zip(assump, soft) if a.value() is False and c.value() is False]
                sat_subset += new_corr_subset # extend sat subset with new corr subset, guaranteed to be disjoint
                hs_solver += cp.sum(new_corr_subset) >= 1 # add new corr subset to hitting set solver
        
        if unsat_hitting_set is None:
            return
        # shrink to a MUS
        hitting_set = set(unsat_hitting_set)
        for c in sorted(hitting_set, key=seenmap.get, reverse=True):
            if c not in hitting_set: # already removed
                continue
            hitting_set.remove(c)
            sat_result = timed_solve(s, deadline, assumptions=list(hitting_set))
            if sat_result is None:
                yield "TIMEOUT", None, time.monotonic() - start_time
                return
            if sat_result:
                hitting_set.add(c)
            else: # UNSAT, shrink to new solver core (clause set refinement)
                hitting_set = set(s.get_core())

        # when first MUS (smallest) is found, reset all weights to zero
        if first:
            first = False
            seenmap = dict(zip(assump, [0]*len(assump)))

        for a in hitting_set:
            seenmap[a] += 1
        # block found MUS in hitting set solver
        hs_solver += ~cp.all(hitting_set)
        yield "MUS", hitting_set, time.monotonic() - start_time